version: '3.8'

services:
  app:
    build: .
    command: gunicorn printoplace.wsgi:application --bind 0:8000
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - ./printoplace/.env
    restart: always
    depends_on:
      - db
  db:
    image: postgres:12
    expose:
      - 5432
    volumes:
      - ../pg_data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=printoplace
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
  nginx:
    build: nginx/.
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    ports:
      - 1337:80
    depends_on:
      - app

volumes:
  db_data:
  static:
  media: