# Generated by Django 3.1.1 on 2020-10-09 06:37

from django.conf import settings
import django.contrib.postgres.fields
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=12, region=None, verbose_name='Номер телефона')),
                ('company_name', models.CharField(blank=True, max_length=64, verbose_name='Название компании')),
                ('is_receiving_news', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None, verbose_name='Список адресов')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('company_files', models.FileField(blank=True, max_length=50, upload_to='company_files/', verbose_name='Документы')),
                ('moderator_message', models.CharField(blank=True, max_length=256, verbose_name='Сообщение для пользователя')),
                ('is_verification', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('category', models.IntegerField(choices=[(1, 'Продукция с переплётом'), (2, 'Флаеры, открытки и плакаты'), (3, 'Календари'), (4, 'Офисное'), (5, 'Рекламная'), (6, 'Для гастрономии и событий')])),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
                ('color', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
                ('material', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristics', django.contrib.postgres.fields.hstore.HStoreField(verbose_name='Характеристики')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Компания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristics', django.contrib.postgres.fields.hstore.HStoreField()),
                ('design', models.FileField(max_length=50, upload_to='design_product/')),
                ('count', models.IntegerField()),
                ('product_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productcompany')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristics', django.contrib.postgres.fields.hstore.HStoreField()),
                ('design', models.FileField(max_length=50, upload_to='design_product/')),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Новый заказ'), (2, 'На согласовании'), (3, 'Отправка'), (4, 'В пути'), (5, 'Прибыл')])),
                ('product_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productcompany')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OldOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_canceled', models.BooleanField()),
                ('characteristics', django.contrib.postgres.fields.hstore.HStoreField()),
                ('design', models.FileField(max_length=50, upload_to='design_product_old/')),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('datetime_expiration', models.DateTimeField(auto_now_add=True)),
                ('product_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productcompany')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
